```{r}
library(readxl)
library(dplyr)
library(visdat)
```

```{r}
# Function to read all sheets in an Excel file and extract the first column
read_excel_data <- function(file_path) {
  sheet_names <- excel_sheets(file_path)
  data_list <- setNames(vector("list", length(sheet_names)), sheet_names)
  
  for (sheet in sheet_names) {
    sheet_data <- read_excel(file_path, sheet = sheet)
    if (ncol(sheet_data) > 0) {
      data_list[[sheet]] <- sheet_data[[1]]  # Extract the first column if not empty
    }
  }
  data_list
}
```

```{r}
# Path to the folder with Excel files
folder_path <- "data/strukturerhebung/"

# Get all Excel files in the folder that match the pattern
file_pattern <- "do-d-40-se_user-syn-(201[0-9])\\.xls"
file_names <- list.files(folder_path, pattern = file_pattern, full.names = TRUE, recursive = TRUE)
file_names <- file_names[!grepl("^~\\$", basename(file_names))]  # Exclude temporary files
```

```{r}
# Read each file and store results in a named list
all_data <- list()
for (file in file_names) {
  all_data[[basename(file)]] <- read_excel_data(file)
}
```
```{r}
# Create a table for the results
file_names <- names(all_data) # file names
sheet_names <- lapply(all_data, names) # sheet names in each file
```


```{r}
variables_zp <- c("HOUSEHOLDYEARLYID", "SECCITIZ", "SECCITIZENSHIP",
                  "NATIONALITYCAT", "NATIONALITYCONTI","TIMEWORKEDPERWEEKSUM", "RESIDENTPERMIT","CURRACTIVITYSTATUSIII",
                       "CURRACTIVITY_FULL", "CURRACTIVITY_PART",
                       "CURRACTIVITY_HOME","IN_EDUCATION",
                       "HIGHESTCOMPLEDU","HIGHESTCOMPLEDUAGGI","AGE","SEX","CURROCCUPATIONISCO")
variables_hh <- c("HOUSEHOLDYEARLYID", "TYPEOFOWNERSHIP","SIZEOFPRIVATEHOUSEHOLD","RENTNET")
variables_list <- unique(c(variables_zp, variables_hh))
```

```{r}
path_save = "questions_answers/nationality_econ_status/"
saveRDS(variables_list, paste0(path_save,"nationality_econ_status.rds"))
saveRDS(variables_zp, paste0(path_save,"variables_zp.rds"))
saveRDS(variables_hh, paste0(path_save,"variables_hh.rds"))
# saveRDS(variables_hhm, paste0(path_save,"variables_hhm.rds"))
```

```{r}
# Create an empty data frame to store results with variables as row names
result_df <- data.frame(matrix(0, nrow = length(variables_zp), ncol = length(file_names)),
                        row.names = variables_zp)
colnames(result_df) <- file_names

# Check if each variable is found in any sheet of each file
for (file in file_names) {
  file_basename <- basename(file)
  
  for (var in variables_list) {
    found <- FALSE
    
    for (sheet in names(all_data[[file_basename]])) {
      sheet_data <- unlist(all_data[[file_basename]][[sheet]])
      
      if (var %in% sheet_data) {
        result_df[var, file_basename] <- 1
        found <- TRUE
        break  # Stop searching this file if variable is found
      }
    }
    
    if (!found) {
      result_df[var, file_basename] <- 0
    }
  }
}
```

```{r}
# Convert the matrix to a DataFrame for convenience
result_df <- as.data.frame(result_df)
saveRDS(result_df, paste0(path_save,"variables_zp.rds"))
# Output the result
print(result_df)
```

```{r}
vis_value(result_df)
```
```{r}
result_df %>% filter(`do-d-40-se_user-syn-2020.xlsx` == 0) %>% rownames(.)
```
