

```{r}
library(tidyverse)
library(readr)
```



```{r}

file_path_2010 <- "data/strukturerhebung/2010_SE_RS_CSV/hh_2010.csv"
file_path_2011 <- "data/strukturerhebung/2011_SE_RS_CSV/hh_2011.csv"

```


```{r}
data_HH_2010 <- read_csv(file_path_2010)

data_HH_2011 <- read_csv(file_path_2011)
```


```{r}

combined_HH <- bind_rows(
  data_HH_2010 %>% mutate(Year = 2010),
  data_HH_2011 %>% mutate(Year = 2011)
)
```


```{r}
data.frame(combined_HH)
```
```{r}
# Check the unique years present
unique_years <- unique(combined_HH$Year)
print("Unique years in combined_HH:")
print(unique_years)
```
```{r}
combined_HH %>% filter(Year == 2011)
```


```{r}
variables_list <- c("AGE", "BIRTH_CANTON", "BIRTH_CTRY",
  "BIRTH_MUN", "BIRTH_MUNCAT", "FAMILYREUNION", "CANCELATIONREASON", 
  "MARITALSTATUS", "CHCOMESFROMCTRY", "NATIONALITYCONTI", "POPULATIONGROUP", "RES_CANTON", 
  "RES_MUN", "RES_1YEARAGO", "RES_2YEARAGO", "RES_3YEARAGO", "RES_4YEARAGO", 
  "RES_5YEARAGO", "RESIDENTPERMIT", 
  "COMPLETEDEDU10", "COMPLETEDEDU11", "COMPLETEDEDU12", "COMPLETEDEDU13",  
  "COMPLETEDEDU3", "COMPLETEDEDU4", "COMPLETEDEDU5", "COMPLETEDEDU6", "COMPLETEDEDU7", 
  "COMPLETEDEDU8", "COMPLETEDEDU9", "HIGHESTCOMPLEDU", "HIGHESTCOMPLEDUAGGI", "HIGHESTCOMPLEDUAGGII", 
  "HIGHESTCOMPLEDUAGGIII", "IN_EDUCATION", "SCHOOL_DISTRICT", "SCHOOL_ADDRESSCTRY", "SCHOOL_CANTON",
  "SCHOOLENPNOGA", 
  "SCHOOLENPSIZE", "SCHOOLLOCUNSECTOR", "LANGUAGEHOME1", "LANGUAGEHOME10", "LANGUAGEHOME11",
  "LANGUAGEHOME12", "LANGUAGEHOME2", "LANGUAGEHOME3", "LANGUAGEHOME4", "LANGUAGEHOME5", 
  "LANGUAGEHOME6", "LANGUAGEHOME7", "LANGUAGEHOME8","LANGUAGEHOME9", "MAINLANGUAGEAGG1", "MAINLANGUAGEAGG10", 
  "MAINLANGUAGEAGG11", "MAINLANGUAGEAGG12", "MAINLANGUAGEAGG13", "MAINLANGUAGEAGG14", 
  "MAINLANGUAGEAGG2", "MAINLANGUAGEAGG3", "MAINLANGUAGEAGG4", "MAINLANGUAGEAGG5", 
  "MAINLANGUAGEAGG6", "MAINLANGUAGEAGG7", "MAINLANGUAGEAGG8", "MAINLANGUAGEAGG9", 
  "MAINLANGUAGEI", "MAINLANGUAGEIAGG", "CITIZBIRTHANDTODAY", "CTRYOFBIRTHOFFATHER", 
  "CTRYOFBIRTHOFMOTHER", "CTRYOFBIRTHOFPARENTS", 
  "MIGRATIONSTATUS", "MIGRATIONSTATUSAGG",  "SECCITIZENSHIP", "TYPEOFCITIZACQ_DI", 
  "YEAROFARRIVAL", "CHARRIVALYEAR", "YEAROFCITIZACQ_SWISS", "DEPFORSCHOOL", 
  "DEPFORSCHOOLCANTON", "DEPFORSCHOOLCTRY", "COMPANY_CANTON", "COMPANY_CTRY", 
  "COMPANY_DISTRICT", "COMPANY_MUN", "COMPANYENPSIZE", "CURRACTIVITYSTATUSI", 
  "CURRACTIVITYSTATUSII", "CURRACTIVITYSTATUSIII", "CURRACTIVITY_FULL", "CURRACTIVITY_PART", 
  "CURRACTIVITY_MULTI", "CURRACTIVITY_DISOCC", "CURRACTIVITY_STUDENT", "CURRACTIVITY_HOME", 
  "CURRACTIVITY_OTHER", "SOCIOECONOMICGROUP", "WORKSTATUS_DETAIL", "WORKSTATUSDETAIL", "HH_COUNTOFMALEMINOR", 
  "HH_COUNTOFMALEU25", "HH_POSITION_IN_HH_BFS", "HH_AGE", "HH_CLASSAGEFIVEYEARS", 
  "HH_BIRTH_CTRY", "HH_FAMILYREUNION", 
  "HH_CANCELATIONREASON", "HH_CLASSOFMARITALSTATUS", "HH_MARITALSTATUS", "HH_SEPARATION", 
  "HH_CHCOMESFROMCTRY", "HH_CHCOMESFROMCTRYAGG", "HH_COMESFROMSTATE", 
  "HH_MUNSTAYDURATION", "HH_MUNSTAYYEARS", 
  "HH_NATIONALITYAGG", "HH_NATIONALITYCAT", "HH_NATIONALITYCONTI", "HH_NATIONALITYSTATE", 
  "HH_POPULATIONGROUP", "HH_REPORTINGHISTMUN", "HH_RES_CANTON", 
  "HH_RES_MUN", 
  "HH_MAINRESCATEGORY",
  "HH_RES_CTRY1YEARAGO", "HH_RES_CTRY2YEARAGO", "HH_RES_CTRY3YEARAGO", 
  "HH_RES_CTRY4YEARAGO", "HH_RES_CTRY5YEARAGO", "HH_RES_HISTMUN1YEARAGO", 
  "HH_RES_HISTMUN2YEARAGO", "HH_RES_HISTMUN3YEARAGO", "HH_RES_HISTMUN4YEARAGO", 
  "HH_RES_HISTMUN5YEARAGO", 
  "HH_RES_CANTON1YEARAGO", "HH_RES_CANTON2YEARAGO", "HH_RES_CANTON3YEARAGO", "HH_RES_CANTON4YEARAGO", 
  "HH_RES_CANTON5YEARAGO", 
  "HH_RES_MUN1YEARAGO", "HH_RES_MUN2YEARAGO", "HH_RES_MUN3YEARAGO",  
  "HH_RES_MUN4YEARAGO", "HH_RES_MUN5YEARAGO",
  "HH_RESIDENTPERMIT", "HH_HIGHESTCOMPLEDUAGGI", "HH_HIGHESTCOMPLEDUAGGII", 
  "HH_HIGHESTCOMPLEDUAGGIII", "HH_MAINLANGUAGEAGG1", "HH_MAINLANGUAGEAGG2", "HH_MAINLANGUAGEAGG3", 
  "HH_MAINLANGUAGEAGG4", "HH_MAINLANGUAGEAGG5", "HH_MAINLANGUAGEAGG6", "HH_MAINLANGUAGEAGG7", 
  "HH_MAINLANGUAGEAGG8", "HH_MAINLANGUAGEAGG9", "HH_MAINLANGUAGEAGG14", 
  "HH_CURRACTIVITYSTATUSI", "HH_CURRACTIVITYSTATUSII", "HH_CURRACTIVITYSTATUSIII","HH_COUNTOFFEMALEMINOR", 
  "HH_COUNTOFFEMALEU25", "HH_COUNTOFPERSON", "HH_FAMU25", "HH_FAMU25_PARENTS", "HH_FAMU18", 
  "HH_FAMU18_PARENTS", "HH_SIZE_16",  "HH_FAMU25_CHILDREN", 
  "HH_FAMU18_CHILDREN", "HH_NATAGG_GROUPS", "HH_NATCAT_GROUPS", "HH_HEDUAGGI_OLD_30", 
  "HH_HEDUAGGI_OLD_25", "HH_HEDUAGGI_COUPLES", "GKATS", "GBAUPS", "GASTWS", "GAZWOT", "NUMBEROFROOMS", "TYPEOFOWNERSHIP", 
  "RENTNET", "WAREAS", "HH_CURRACTSTI_GROUPS", "HH_OCC_MODEL")

```


