```{r}
library(readxl)
```

```{r}
# We create a function for reading all sheets and extracting the first column
read_excel_data <- function(file_path) {
  # We get all sheet names
  sheet_names <- excel_sheets(file_path)
  
  # Dictionary for storing results
  data_list <- list()
  
  # We go through all the sheets and extract the first column
  for (sheet in sheet_names) {
    # Read data from each sheet
    sheet_data <- read_excel(file_path, sheet = sheet)
    
    # If the sheet is not empty, extract the first column
    if (ncol(sheet_data) > 0) {
      data_list[[sheet]] <- sheet_data[[1]]
    }
  }
  
  return(data_list)
}
```

```{r}
# Path to the folder with Excel files
folder_path <- "data/strukturerhebung/"
folder_path
```

```{r}
# Get all Excel files in the folder
file_pattern <- "do-d-40-se_user-syn-(201[0-9]|2020|2021)\\.xls"
file_names <- list.files(folder_path, pattern = file_pattern, full.names = TRUE, recursive = TRUE)
file_names
```

```{r}
# Create a dictionary to store all the results
all_data <- list()
```

```{r}
# Read each file and store the result
for (file in file_names) {
  all_data[[basename(file)]] <- read_excel_data(file)
}

# The result will be stored in all_data, which is a list
# all_data[[file_name]][[sheet_name]] gives access to the first column of each sheet
```
```{r}
variables_list <- c("AGE", "BIRTH_CANTON", "BIRTH_CTRY",
  "BIRTH_MUN", "BIRTH_MUNCAT", "FAMILYREUNION", "CANCELATIONREASON", 
  "MARITALSTATUS", "CHCOMESFROMCTRY", "NATIONALITYCONTI", "POPULATIONGROUP", "RES_CANTON", 
  "RES_MUN", "RES_1YEARAGO", "RES_2YEARAGO", "RES_3YEARAGO", "RES_4YEARAGO", 
  "RES_5YEARAGO", "RESIDENTPERMIT", 
  "COMPLETEDEDU10", "COMPLETEDEDU11", "COMPLETEDEDU12", "COMPLETEDEDU13", "COMPLETEDEDU2", 
  "COMPLETEDEDU3", "COMPLETEDEDU4", "COMPLETEDEDU5", "COMPLETEDEDU6", "COMPLETEDEDU7", 
  "COMPLETEDEDU8", "COMPLETEDEDU9", "HIGHESTCOMPLEDU", "HIGHESTCOMPLEDUAGGI", "HIGHESTCOMPLEDUAGGII", 
  "HIGHESTCOMPLEDUAGGIII", "IN_EDUCATION", "SCHOOL_DISTRICT", "SCHOOL_GREATREG", 
  "SCHOOL_LABMARKREG", "SCHOOL_LANGREG", "SCHOOL_URBRUR", "SCHOOL_URBRURDI", "SCHOOLENPNOGA", 
  "SCHOOLENPSIZE", "SCHOOLLOCUNSECTOR", "LANGUAGEHOME", "MAINLANGUAGEAGG1", "MAINLANGUAGEAGG10", 
  "MAINLANGUAGEAGG11", "MAINLANGUAGEAGG12", "MAINLANGUAGEAGG13", "MAINLANGUAGEAGG14", 
  "MAINLANGUAGEAGG2", "MAINLANGUAGEAGG3", "MAINLANGUAGEAGG4", "MAINLANGUAGEAGG5", 
  "MAINLANGUAGEAGG6", "MAINLANGUAGEAGG7", "MAINLANGUAGEAGG8", "MAINLANGUAGEAGG9", 
  "MAINLANGUAGEI", "MAINLANGUAGEIAGG", "CITIZBIRTHANDTODAY", "CTRYOFBIRTHOFFATHER", 
  "CTRYOFBIRTHOFMOTHER", "CTRYOFBIRTHOFPARENTS", "CTRYOFSECCITIZTODAY", "EVERRESIDEDABROAD", 
  "MIGRATIONSTATUS", "MIGRATIONSTATUSAGG", "SECCITIZ", "SECCITIZTODAY", "TYPEOFCITIZACQ_DI", 
  "YEAROFARRIVAL", "CHARRIVALYEAR", "YEAROFCITIZACQ_SWISS", "DEPFORSCHOOLMSREG", 
  "DEPFORSCHOOLURBRUR", "DEPFORSCHOOLURBRURDI", "COMPANY_CANTON", "COMPANY_CTRY", 
  "COMPANY_DISTRICT", "COMPANY_MUN", "COMPANYENPSIZE", "CURRACTIVITYSTATUSI", 
  "CURRACTIVITYSTATUSII", "CURRACTIVITYSTATUSIII", "CURRACTIVITY_FULL", "CURRACTIVITY_PART", 
  "CURRACTIVITY_MULTI", "CURRACTIVITY_DISOCC", "CURRACTIVITY_STUDENT", "CURRACTIVITY_HOME", 
  "CURRACTIVITY_OTHER", "SOCIOECONOMICGROUP", "WORKSTATUS", "HH_COUNTOFMALEMINOR", 
  "HH_COUNTOFMALEU25", "HH_POSITION_IN_HH_BFS", "HH_AGE", "HH_CLASSAGEFIVEYEARS", 
  "HH_BIRTH_CTRY", "HH_FAMILYREUNION", 
  "HH_CANCELATIONREASON", "HH_CLASSOFMARITALSTATUS", "HH_MARITALSTATUS", "HH_SEPARATION", 
  "HH_CHCOMESFROMCTRY", "HH_CHCOMESFROMCTRYAGG", "HH_COMESFROMSTATE", 
  "HH_MUNSTAYDURATION", "HH_MUNSTAYYEARS", 
  "HH_NATIONALITYAGG", "HH_NATIONALITYCAT", "HH_NATIONALITYCONTI", "HH_NATIONALITYSTATE", 
  "HH_POPULATIONGROUP", "HH_REPORTINGHISTMUN", "HH_RES_CANTON", 
  "HH_RES_MUN", 
  "HH_MAINRESCATEGORY",
  "HH_RES_CTRY1YEARAGO", "HH_RES_CTRY2YEARAGO", "HH_RES_CTRY3YEARAGO", 
  "HH_RES_CTRY4YEARAGO", "HH_RES_CTRY5YEARAGO", "HH_RES_HISTMUN1YEARAGO", 
  "HH_RES_HISTMUN2YEARAGO", "HH_RES_HISTMUN3YEARAGO", "HH_RES_HISTMUN4YEARAGO", 
  "HH_RES_HISTMUN5YEARAGO", 
  "HH_RES_CANTON1YEARAGO", "HH_RES_CANTON2YEARAGO", "HH_RES_CANTON3YEARAGO", "HH_RES_CANTON4YEARAGO", 
  "HH_RES_CANTON5YEARAGO", 
  "HH_RES_MUN1YEARAGO", "HH_RES_MUN2YEARAGO", "HH_RES_MUN3YEARAGO",  
  "HH_RES_MUN4YEARAGO", "HH_RES_MUN5YEARAGO",
  "HH_RESIDENTPERMIT", "HH_HIGHESTCOMPLEDUAGGI", "HH_HIGHESTCOMPLEDUAGGII", 
  "HH_HIGHESTCOMPLEDUAGGIII", "HH_MAINLANGUAGEAGG1", "HH_MAINLANGUAGEAGG2", "HH_MAINLANGUAGEAGG3", 
  "HH_MAINLANGUAGEAGG4", "HH_MAINLANGUAGEAGG5", "HH_MAINLANGUAGEAGG6", "HH_MAINLANGUAGEAGG7", 
  "HH_MAINLANGUAGEAGG8", "HH_MAINLANGUAGEAGG9", "HH_MAINLANGUAGEAGG14", "HH_MAINLANGUAGEIAGG", 
  "HH_CURRACTIVITYSTATUSI", "HH_CURRACTIVITYSTATUSII", "HH_CURRACTIVITYSTATUSIII","HH_COUNTOFFEMALEMINOR", 
  "HH_COUNTOFFEMALEU25", "HH_COUNTOFPERSON", "HH_FAMU25", "HH_FAMU25_PARENTS", "HH_FAMU18", 
  "HH_FAMU18_PARENTS", "HH_SIZE_16", "SIZEOFPRIVATEHOUSEHOLD", "HH_FAMU25_CHILDREN", 
  "HH_FAMU18_CHILDREN", "HH_NATAGG_GROUPS", "HH_NATCAT_GROUPS", "HH_HEDUAGGI_OLD_30", 
  "HH_HEDUAGGI_OLD_25", "HH_HEDUAGGI_COUPLES", "GKATS", "GSEL", "GBAUPS", "GASTWS", 
  "GHEIZS", "GENHZS", "GWWVS", "GENWWS", "GAZWOT", "NUMBEROFROOMS", "TYPEOFOWNERSHIP", 
  "RENTNET", "WAREAS", "HH_CURRACTSTI_GROUPS", "HH_OCC_MODEL")
```

```{r}
# Create a table for the results
file_names <- names(all_data) # file names
sheet_names <- lapply(all_data, names) # sheet names in each file
file_names
```

```{r}
# Prepare an empty matrix for the results
result_matrix <- matrix(0, nrow = length(variables_list), ncol = length(file_names))
rownames(result_matrix) <- variables_list
colnames(result_matrix) <- file_names
```

```{r}
# Checking each sheet in the file
for (file_idx in seq_along(file_names)) {
  file <- file_names[file_idx]
  for (var_idx in seq_along(variables_list)) {
    var <- variables_list[var_idx]
    
    found <- FALSE  # Flag to check if the variable is found
    
    for (sheet in sheet_names[[file]]) {
      # Get the data from the sheet
      sheet_data <- all_data[[file]][[sheet]]
      
      # Check if the sheet data is a list or vector
      if (is.list(sheet_data) || is.vector(sheet_data)) {
        # Check if the variable is present in this list or vector
        if (var %in% unlist(sheet_data)) {  # unlist converts the list into a vector
          found <- TRUE
          break  # Exit the loop if found
        }
      }
    }
    
    # Store the result: 1 if found, 0 if not found
    if (found) {
      result_matrix[var_idx, file_idx] <- 1
    } else {
      result_matrix[var_idx, file_idx] <- 0
    }
  }
}
```

```{r}
# Convert the matrix to a DataFrame for convenience
result_df <- as.data.frame(result_matrix)

# Output the result
print(result_df)
```
```{r}
library(visdat)
```

```{r}
vis_value(result_df)
```
```{r}
missing_values_2015 <- result_df %>% filter(`do-d-40-se_user-syn-2015.xls` == 0)
missing_values_2015
```
```{r}
# Отримати назви індексів (рядків) з датафрейму
row_names <- rownames(missing_values_2015)
print(row_names)
```
```{r}
# Для отримання значень із першого стовпця
values <- missing_values_2015 %>% pull(1)
values
```
```{r}
 result_df %>% filter(`do-d-40-se_user-syn-2020.xlsx` == 0) %>% rownames(.)
```


```{r}
# Create a list to store the results with detailed information
result_list <- list()

# Checking each sheet in each file
for (file_idx in seq_along(file_names)) {
  file <- file_names[file_idx]
  for (var_idx in seq_along(variables_list)) {
    var <- variables_list[var_idx]
    
    # Flag to check if the variable is found on any sheet
    found_anywhere <- FALSE  
    
    for (sheet in sheet_names[[file]]) {
      # Get the data from the sheet
      sheet_data <- all_data[[file]][[sheet]]
      
      # Check if the sheet data is a list or vector
      if (is.list(sheet_data) || is.vector(sheet_data)) {
        # Check if the variable is present in this list or vector
        if (var %in% unlist(sheet_data)) {
          # Add the information to result_list for each sheet where the variable is found
          result_list[[length(result_list) + 1]] <- data.frame(
            Variable = var,
            File = file,
            Sheet = sheet,
            Found = 1
          )
          
          found_anywhere <- TRUE
          # Continue checking other sheets, don't break the loop
        }
      }
    }
    
    # If the variable was not found in any sheet of the file, still add the result
    if (!found_anywhere) {
      result_list[[length(result_list) + 1]] <- data.frame(
        Variable = var,
        File = file,
        Sheet = NA,
        Found = 0
      )
    }
  }
}

# Combine the list into a data frame
result_df_detailed <- do.call(rbind, result_list)

# Output the result
print(result_df_detailed)

```
```{r}
library(dplyr)

# Filter rows where Sheet is "ZP"
filtered_ZP <- result_df_detailed %>% filter(Sheet == "ZP")

# Output the result
filtered_ZP
```
```{r}
c(filtered_ZP$Variable) %>% unique()
```


```{r}
# Filter rows where Sheet is "HH"
filtered_HH <- result_df_detailed %>% filter(Sheet == "HH")

# Output the result
filtered_HH
```
```{r}
library(stringr)
filtered_ZP_by_year <- result_df_detailed %>% filter(Sheet == "ZP", str_detect(File, "2020"))
filtered_ZP_by_year
```

```{r}
library(stringr)
filtered_by_year <- result_df_detailed %>%
  filter(str_detect(File, "2015")) %>%
  arrange(Variable)  
filtered_by_year
```
```{r}
c(filtered_ZP_by_year$Variable)
```



```{r}
"HH_FAMU18_CHILDREN" %in% filtered_HH$Variable
"HH_FAMU18_PARENTS" %in% filtered_HH$Variable
```
```{r}
all_parentsNchildren <- combined_data[, c("HH_FAMU18_CHILDREN", "HH_FAMU18_PARENTS")]
all_parentsNchildren
```

