```{r, message=FALSE}
library(dplyr)
library(ggplot2)
library(purrr)
```

```{r}
zp_merged_data <- read.csv("zp_merged_data.csv")
hh_merged_data <- read.csv("hh_merged_data.csv")
hhm_merged_data <- read.csv("hhm_merged_data.csv")
```

```{r}
decode <- function(df, var, decode_mapping) {
  # Перетворюємо ключі у списку на текст
  for (key in names(decode_mapping)) {
    value <- decode_mapping[[key]]
    df <- df %>%
      mutate({{ var }} := case_match(
        as.character({{ var }}),  # Перетворюємо значення змінної на текст
        key ~ value,              # Зіставляємо ключ зі значенням
        .default = as.character({{ var }})  # Залишаємо оригінальне значення, якщо немає відповідності
      ))
  }
  return(df)
}
```

```{r}
box_plot <- function(df,cat,value){
  df %>% 
    filter({{cat}}>0 & {{value}}> 0) %>% 
    ggplot(aes(x={{cat}}, y={{value}}, fill = {{cat}}))+
    geom_boxplot(na.rm = TRUE)+
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, size = 10), 
      axis.text.y = element_text(size = 10),                       
      legend.text = element_text(size = 10),                    
      plot.margin = margin(10, 20, 10, 10)  
  )
}
```

```{r}
work_time_by_two_categories <- function(df, cat1, cat2, sort_levels = NULL){
  for (year in 2010:2021){
    data_filtered <- {{df}} %>% 
      filter(YEAR_QUIZ == year) %>% 
      filter(!is.na({{cat1}}) & TIMEWORKEDPERWEEKSUM > 0 
             & !is.na({{cat2}})) %>% 
      group_by({{cat1}}, {{cat2}})
    if (!is.null(sort_levels)) {
      data_filtered <- data_filtered %>%  mutate({{cat2}} := factor({{cat2}},levels = sort_levels))
    } 
    chart <- data_filtered %>% 
      summarise(average_time_worked = median(TIMEWORKEDPERWEEKSUM, na.rm = TRUE), .groups = "drop") %>%
      ggplot(aes(x={{cat2}}, y = average_time_worked, fill={{cat1}}))+
      geom_bar(stat = "identity", position = "dodge")+
      geom_text(aes(label = round(average_time_worked, 1)),
                position = position_dodge(width = 0.9), 
                vjust = 2,
                size = 3) +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 10), 
        axis.text.y = element_text(size = 10),                       
        legend.text = element_text(size = 10),                    
        plot.margin = margin(10, 20, 10, 10)  
      )
    print(chart)
  }
}
```

```{r}
generate_charts_by_occupation <- function(data, occupation_column, nationality_column) {

  for (year in 2010:2021) {
    chart <- data %>% 
      filter(YEAR_QUIZ == year & 
               !is.na({{ occupation_column }}) & 
               !is.na({{ nationality_column }})) %>% 
      ggplot(aes(x = {{ occupation_column }}, fill = {{ nationality_column }})) +
      geom_bar(position = "fill", na.rm = TRUE) +
      geom_text(
        aes(label = scales::percent(
          round(after_stat(count) / tapply(after_stat(count), 
                                           after_stat(x), sum)[after_stat(x)], 2))),
        stat = "count",
        position = position_fill(vjust = 0.5),
        size = 3
      ) +
      labs(
        title = paste("Year:", year),
        x = "Occupation",
        y = "Proportion"
      ) +
      theme(
        axis.text.x = element_text(angle = 45, hjust = 1, size = 10),
        axis.text.y = element_text(size = 10),
        legend.text = element_text(size = 10),
        plot.margin = margin(10, 20, 10, 10)
      )
    
    print(chart)
  }
}
```

```{r}
summary(zp_merged_data)
```
```{r}
summary(hh_merged_data)
```
```{r}
summary(hhm_merged_data)
```
```{r}
selected_data <- zp_merged_data %>% select(HIGHESTCOMPLEDU, HIGHESTCOMPLEDUAGGII, AGE,
                                           HOUSEHOLDYEARLYID, NATIONALITYAGG, NATIONALITYCAT, 
                          NATIONALITYCONTI, NATIONALITYID, NATIONALITYSTATE,
                          WORKSTATUS, WORKSTATUS_DETAIL, TIMEWORKEDPERWEEKSUM,STATUSINEMPLOYMENT, 
                          STATUSINEMPL_DETAIL, MIGRATIONSTATUS, RESIDENTPERMIT, YEAR_QUIZ,
                          CURROCCUPATIONISCO,CURROCCUPATIONISCOAGG)
```

```{r}
# Empty dataframe to store results
results <- data.frame(
  Count_unique = integer(),
  Total = integer(),
  Year = integer()
)

# Loop through years
for (year in 2010:2021) {
  # Count unique rows for the current year
  count_unique <- selected_data %>%
    select(HOUSEHOLDYEARLYID, YEAR_QUIZ) %>%
    filter(YEAR_QUIZ == year) %>%
    distinct() %>%
    count()
  
  # Count all rows for the current year
  total <- selected_data %>%
    select(HOUSEHOLDYEARLYID, YEAR_QUIZ) %>%
    filter(YEAR_QUIZ == year) %>%
    count()
  
  # Add results to the results dataframe
  results <- rbind(
    results,
    data.frame(
      Count_unique = count_unique$n,  # Extract value from count()
      Total = total$n,                # Extract value from count()
      Year = year
    )
  )
}

# Display the results table
print(results)
```
```{r}
summary(selected_data)
```
```{r}
# Завантаження бібліотек
library(ggplot2)
library(reshape2)

# Обробка даних: вибір лише числових колонок
numeric_data <- zp_merged_data[sapply(zp_merged_data, is.numeric)]
# Обчислення кореляційної матриці
numeric_data[is.na(numeric_data)] <- 0
correlation_matrix <- cor(numeric_data)

# Перетворення матриці в довгий формат для ggplot2
correlation_long <- melt(correlation_matrix)

# Побудова теплової карти
heatmap_plot <- ggplot(data = correlation_long, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  geom_text(aes(label = round(value, 2)), color = "black", size = 3) + # Додавання значень кореляції
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) + # Вибір кольорової гами
  theme_minimal() +
  labs(title = "Correlation Heatmap",
       x = "Variables",
       y = "Variables",
       fill = "Correlation") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# Відображення графіка
print(heatmap_plot)
```
```{r}
# Обчислення кореляційної матриці
correlation_matrix <- cor(numeric_data, use = "complete.obs")

# Вибір кореляцій для TIMEWORKEDPERWEEKSUM
timeworked_correlations <- correlation_matrix["TIMEWORKEDPERWEEKSUM", ]

# Видалення самої змінної TIMEWORKEDPERWEEKSUM (кореляція з собою завжди 1)
timeworked_correlations <- timeworked_correlations[names(timeworked_correlations) != "TIMEWORKEDPERWEEKSUM"]

# Сортування за значеннями кореляції
sorted_correlations <- sort(timeworked_correlations, decreasing = TRUE)

# Отримання топ-5 позитивних і негативних кореляцій
top_5_positive <- head(sorted_correlations, 10)
top_5_negative <- tail(sorted_correlations, 10)

# Вивід результатів
print("Топ-5 позитивних кореляцій:")
print(top_5_positive)

print("Топ-5 негативних кореляцій:")
print(top_5_negative)
```


```{r}
selected_data <- selected_data %>% mutate(
  AGE_GROUP = case_when(AGE < 18 ~ "<18",
                        AGE >= 18 & AGE <= 30 ~ "18-30",
                        AGE >= 31 & AGE <= 40 ~ "31-40",
                        AGE >= 41 & AGE < 50 ~ "41-50",
                        AGE >= 51 ~ "51+"),
)
```

```{r}
head(selected_data %>%  select(AGE, AGE_GROUP))
```
```{r}
selected_data <- decode(selected_data, TIMEWORKEDPERWEEKSUM, list(
    "-9" = NA,
    "-8" = NA,
    "-7" = NA
  )
)
selected_data$TIMEWORKEDPERWEEKSUM <- as.numeric(as.character(selected_data$TIMEWORKEDPERWEEKSUM))
```


```{r}
selected_data$TIMEWORKEDPERWEEKSUM %>% unique()
```


```{r}
mean_age <- mean(selected_data$TIMEWORKEDPERWEEKSUM)
median_age <- median(selected_data$TIMEWORKEDPERWEEKSUM)

selected_data %>% filter(!is.na(TIMEWORKEDPERWEEKSUM)) %>% 
  ggplot(aes(x = TIMEWORKEDPERWEEKSUM)) +
    geom_density(fill = "skyblue", alpha = 0.5) +  # Щільність розподілу
    labs(title = "Work time per week", x = "time", y = "density") +
    theme_minimal(base_size = 14)
```


```{r}
selected_data <- selected_data %>% mutate(
  WORK_TIME_GROUP = case_when(TIMEWORKEDPERWEEKSUM < 20 ~ "<50%",
                        TIMEWORKEDPERWEEKSUM >= 21 & TIMEWORKEDPERWEEKSUM <= 27 ~ "50-70%",
                        TIMEWORKEDPERWEEKSUM >= 29 & TIMEWORKEDPERWEEKSUM <= 36 ~ "70-90%",
                        TIMEWORKEDPERWEEKSUM >= 37 & TIMEWORKEDPERWEEKSUM <= 40 ~ "90-100%",
                        TIMEWORKEDPERWEEKSUM >= 41 & TIMEWORKEDPERWEEKSUM <= 44 ~ "100-110%",
                        TIMEWORKEDPERWEEKSUM >= 45 & TIMEWORKEDPERWEEKSUM <= 48 ~ "110-120%",
                        TIMEWORKEDPERWEEKSUM >= 49 ~ ">120%"),
)
```

```{r}
selected_data <- decode(selected_data, CURROCCUPATIONISCOAGG, list(
    "1" = "Führungskräfte",
    "2" = "Akademische Berufe",
    "3" = "Techniker und gleichrangige Berufe",
    "4" = "Bürokräfte und verwandte Berufe",
    "5" = "Dienstleistungsberufe und Verkäufer",
    "6" = "Fachkräfte in Land- und Forstwirtschaft",
    "7" = "Handwerks- und verwandte Berufe",
    "8" = "Anlagen und Maschinenbediener, Montierer",
    "9" = "Hilfsarbeitskräfte",
    "0" = "Angehörige der regulären Streitkräfte",
    "-9" = NA,
    "-8" = NA,
    "-7" = NA
  )
)
  
```


```{r}
selected_data <- decode(selected_data, NATIONALITYCONTI, list(
    "1" = "Schweiz",
    "2" = "Mitgliedstaat der Europäischen Union (EU)",
    "3" = "Mitgliedstaat der EFTA",
    "4" = "Anderer europäischer Staat",
    "5" = "Afrika",
    "6" = "Nordamerika",
    "7" = "Lateinamerika und Karibik",
    "8" = "Asien",
    "9" = "Ozeanien",
    "-1" = "Staatenlos",
    "-9" = NA
  )
)
```

```{r}
selected_data <- decode(selected_data, NATIONALITYCAT, list(
    "1" = "Schweiz",
    "2" = "Ausländer",
    "-9" = NA
  )
)
```

```{r}
selected_data <- selected_data %>%
  mutate(
    WORKSTATUS_DETAIL = if_else(
      YEAR_QUIZ > 2014 & WORKSTATUS_DETAIL %in% c(121, 122),
      case_match(WORKSTATUS_DETAIL, 121 ~ 111, 122 ~ 112),  
      WORKSTATUS_DETAIL                                   
    )
  )
```

```{r}
selected_data <- decode(selected_data, HIGHESTCOMPLEDUAGGII, list(
    "1" = "No school / 1-7 years",
    "2" = "8-9 years of school / Bridge program",
    "3" = "Vocational training / Vocational school",
    "4" = "General education / Matura",
    "5" = "Higher vocational education / Technical school",
    "6" = "University / Higher education",
    "-9" = NA
  )
)
```

```{r}
selected_data <- decode(selected_data, RESIDENTPERMIT, list(
    "1" = "A",
    "2" = "B",
    "3" = "C",
    "4" = "Ci",
    "5" = "F",
    "6" = "G",
    "7" = "L",
    "8" = "N",
    "9" = "S",
    "10" = "Meldepflichtige",
    "11" = "Funktionär",
    "12" = "Funktionär",
    "13" = NA,
    "-2" = "Schweiz",
    "-6" = NA,
    "-8" = NA,
    "-9" = NA
  )
)
```


```{r}
selected_data <- decode(selected_data, WORKSTATUS_DETAIL, list(
  "111" = "Selbständige mit Angestellten",
  "112" = "Selbständige ohne Angestellte",
  "113" = "Mitarbeitende Familienmitglieder",
  "121" = "Arbeitnehmer in Unternehmensleitung",
  "131" = "Arbeitnehmer in Unternehmensleitung",
  "124" = "Arbeitnehmer im mittleren und unteren Kader",
  "134" = "Arbeitnehmer im mittleren und unteren Kader",
  "125" = "Arbeitnehmer ohne Vorgesetztenfunktion",
  "135" = "Arbeitnehmer ohne Vorgesetztenfunktion",
  "126" = "Arbeitnehmer in geschützter Werkstatt",
  "136" = "Arbeitnehmer in geschützter Werkstatt",
  "127" = "Lernende in der dualen beruflichen Grundbildung",
  "137" = "Lernende in der dualen beruflichen Grundbildung",
  "128" = "Arbeitnehmer ohne weitere Angaben",
  "130" = "Erwerbstätige ohne weitere Angaben",
  "200" = "Erwerbslose",
  "301" = "Nichterwerbspersonen in Ausbildung",
  "302" = "Nichterwerbspersonen mit freiwilliger Tätigkeit",
  "303" = "Hausfrauen/Hausmänner",
  "304" = "Rentner, Pensionierte",
  "305" = "Invalide oder teilinvalide Nichterwerbspersonen",
  "306" = "Übrige Nichterwerbspersonen",
  "-9" = NA
  
)
)
```


```{r}
head(selected_data)
```



```{r}
box_plot(selected_data, NATIONALITYCONTI, TIMEWORKEDPERWEEKSUM)
```
```{r}
box_plot(selected_data, NATIONALITYCAT, TIMEWORKEDPERWEEKSUM)
```
```{r}
work_time_by_two_categories(selected_data, NATIONALITYCAT, CURROCCUPATIONISCOAGG)
```

```{r}
generate_charts_by_occupation(selected_data, CURROCCUPATIONISCOAGG, NATIONALITYCAT)
```
```{r}
without_swiss <- selected_data %>% 
  filter(RESIDENTPERMIT != "Schweiz")
generate_charts_by_occupation(without_swiss, CURROCCUPATIONISCOAGG, RESIDENTPERMIT)
```



```{r}
work_time_by_two_categories(selected_data, NATIONALITYCONTI, HIGHESTCOMPLEDUAGGII, c("No school / 1-7 years", 
                           "8-9 years of school / Bridge program",
                           "Vocational training / Vocational school",
                           "General education / Matura",
                           "Higher vocational education / Technical school",
                           "University / Higher education"))
```


```{r}
work_time_by_two_categories(selected_data, NATIONALITYCAT, HIGHESTCOMPLEDUAGGII, c("No school / 1-7 years", 
                           "8-9 years of school / Bridge program",
                           "Vocational training / Vocational school",
                           "General education / Matura",
                           "Higher vocational education / Technical school",
                           "University / Higher education"))
```

```{r}
work_time_by_two_categories(selected_data, NATIONALITYCAT, CURROCCUPATIONISCOAGG)
```
```{r}
work_time_by_two_categories(selected_data, RESIDENTPERMIT, CURROCCUPATIONISCOAGG)

```



```{r}
generate_charts_by_occupation(selected_data, CURROCCUPATIONISCOAGG, NATIONALITYCAT)
```

```{r}
generate_charts_by_occupation(selected_data, WORKSTATUS_DETAIL, NATIONALITYCAT)
```



